### ISSUE TITLE
riotboot: tests

### ISSUE THREAD

**Issue by danpetry** [RIOT-OS/Release-Specs#110]
Currently we're not testing riotboot as part of the release specs. We should include this. Running the two current tests in tests/ for all supported board (automatedly, if possible) would be sufficient IMO.

**Comment by miri64** [comment]
Isn't this included somewhat in Task 2.2-4 combined with Task 99? Or do you want to make it more explicit that it **must** be tested for all supported boards.

**Comment by danpetry** [comment]
yes you're right, just catching up on the test scope atm, thanks for the info.
