### ISSUE TITLE
Test 02: several tests fail when run together with the other tests, but pass individually

### ISSUE THREAD

**Issue by danpetry** [RIOT-OS/Release-Specs#126]
The failures can happen - but don't always happen - when `02-compile-and-test-for-board.py` is run without any `--applications` argument. With the `--applications` argument, they pass.

These tests include:

- xtimer_hang and xtimer_usleep for native
- libfixmath for iotlab-m3

**Comment by MrKevinWeiss** [comment]
@cladmi, have you noticed this?  Is this fixed with the new scripts?

**Comment by cladmi** [comment]
This looks like an issue with the tests themselves. The fact that it failed when executing multiple tests and worked once when done alone must just be a coincidence, or a loaded machine.

For `xtimer_usleep` the test is not enabled on native in `CI` as it randomly fails. But I ignore `TEST_ON_CI_WHITELIST` as many tests are currently not there.

`libfixmath` is not surprising and I think it comes from the test, it may fail when the previous test just puts some output.

**Comment by cladmi** [comment]
The script is just a `for` loop.

**Comment by MrKevinWeiss** [comment]
So do we close?

**Comment by cladmi** [comment]
I would say yes with the current description.

**Comment by cladmi** [comment]
I noticed the script is still included in the Release-Specs repository instead of using the one in RIOT. I will do a PR to update this.

**Comment by MrKevinWeiss** [comment]
Thanks.  Closing!
