### ISSUE TITLE
RFC: Add tests for IPv6 fragmentation

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/Release-Specs#137]
With IPv6 fragmentation and reassembly merged (https://github.com/RIOT-OS/RIOT/pull/11623 and https://github.com/RIOT-OS/RIOT/pull/11596 respectively) during the 2019.10 release cycle, I think it makes sense to extend the release specifications for packets of sizes (MTU, 2*MTU]. Specifically I would extend `03`, `04` and `07` with one task each to ping with packets with e.g. 2 KiB payload size.

All weird corner cases should already be covered by the `tests/gnrc_ipv6_ext_frag` application (which _should_ be covered by `02`, but who knows, since it requires `sudo` and people tend to skip tests that are not auto-run ;-P). However, I prefer to have at least some "in-the-wild" tests done during the release testing.

TBH, I personally never tested IPv6 + 6LoWPAN fragmentation (but AFAIK @benpicco did during the testing of https://github.com/RIOT-OS/RIOT/pull/11623 *[edit]after rereading his review comment I'm less sure[/edit]*), so we have to see if the `04` extension works as expected and I don't believe multihop (`07`) was properly tested yet (`tests/gnrc_ipv6_ext_frag` tests forwarding of fragments though). I would thus suggest that the `04` and `07` extensions should be marked as experimental at least for the first RC they are tested in, in case some weird side effects arise.

**Comment by leandrolanzieri** [comment]
+1 for extending the tests and making those tasks experimental for now in `04` and `07`, I think we should test this feature in multiple conditions.

On a separate matter, tasks 4.(5-8) still remain experimental? They seem to have been passing, @aabadie ?

**Comment by miri64** [comment]
Ok, then I prepare a PR with the specifications.

**Comment by miri64** [comment]
Good that we test this. Pinging with 2KiB already maxes out the packet buffer xD

**Comment by miri64** [comment]
> On a separate matter, tasks 4.(5-8) still remain experimental? They seem to have been passing, @aabadie ?

Let's discuss this in a separate issue, please.

**Comment by kb2ma** [comment]
I just merged #137. With @leandrolanzieri  and @fjmolinas agreement here, let's close this issue.
