### ISSUE TITLE
RFC: Task 8: Remove emb6 interop tests

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/Release-Specs#141]
With emb6 being deprecated since https://github.com/RIOT-OS/RIOT/pull/12389 I'm wondering if it still makes sense to include emb6 in the release testing until 2020.06 or not.

**Comment by fjmolinas** [comment]
> With emb6 being deprecated since RIOT-OS/RIOT#12389 I'm wondering if it still makes sense to include emb6 in the release testing until 2020.06 or not.

That depends, does deprecation mean that we only keep the code base until 2020.06? or that we also have stoped supporting it. If its the later then I would remove the task.

**Comment by miri64** [comment]
> That depends, does deprecation mean that we only keep the code base until 2020.06? or that we also have stopped supporting it. If its the later then I would remove the task.

Apart from adaptation to API changes and fixes to the wrappers there was no active development on it for quite a while which was the reason for its deprecation. Would you call that "stop supporting it" :grinning:?

**Comment by fjmolinas** [comment]
> Apart from adaptation to API changes and fixes to the wrappers there was no active development on it for quite a while which was the reason for its deprecation (see linked PR in OP for more details). Would you call that "stop supporting it" grinning?

What I mean is that if a bug shows up before 2020.06, will we attempt to fix it? My question goes more towards what kind of engagement to we have against deprecated code? Would we want to fix and issue?, just list it? or not care at all? 

Maybe this is documented somewhere?

**Comment by miri64** [comment]
> What I mean is that if a bug shows up before 2020.06, will we attempt to fix it? My question goes more towards what kind of engagement to we have against deprecated code? Would we want to fix and issue?, just list it? or not care at all?

In general I think we should decide the meaning of deprecation with regards to bugs on a case-by-case basis.

In the case of `emb6`: if the unlikely case that a bug shows up until 2020.06 (despite of it being stale it seems to be quite stable), it really depends on where the bug lies and who will fix it (for sake of brevity I assume its me ;-)): If the bug is within the emb6 code base, I'm not willing to fix it, as I already mentioned in https://github.com/RIOT-OS/RIOT/pull/12389 that the upstream code base is stale and heavy rework needs to be done to make a more current version of emb6 run with RIOT. If the bug is in our porting code, it really depends on the severity and my time ;-).

**Comment by miri64** [comment]
Another question is: if we don't do the release tests anymore, will we notice that there is a bug?

**Comment by fjmolinas** [comment]
> Another question is: if we don't do the release tests anymore, will we notice that there is a bug?

That was the reasoning behind my question. Do we want to notice bugs? Should we document known issues in deprecated libs?

> In general I think we should decide the meaning of deprecation with regards to bugs on a case-by-case basis.

But if we deprecated something I guess ultimately it shouldn't block a release. So in any case either it shouldn't be part of the spec, or be non-blocking.

**Comment by miri64** [comment]
Mh, yeah with this in mind I'd say keep it, but make it non-blocking is the way to go.

**Comment by kb2ma** [comment]
At a glance, the scope of testing looks like two tasks for 08-interop. This is a small investment. If there are any bugs, I would handle them on a case by case basis.

**Comment by miri64** [comment]
Another thing to think about is that this frees up number space (they are the last tests in 08-interop). If we add new tests before removing this, there is either a gap or we need to renumber them, which might lead to some confusion.

**Comment by miri64** [comment]
`emb6` was removed in RIOT for the next release, so I opened #157
