### ISSUE TITLE
Release 2017.01 - RC2

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/Release-Specs#38]
This issue lists the status of all tests for the [Release Candidate 2 of the 2017.01](https://github.com/RIOT-OS/RIOT/releases/tag/2017.01-RC2) release.

Specs tested:
- [x] [01-CI](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md), @PeterKietzmann
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-01)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-02)
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-03)
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-04)
- [x] [02-Tests](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md) 
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md#task-01), @A-Paul #39
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md#task-02), @BytesGalore #40
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md#task-03), @PeterKietzmann  #41
- [x] [03-Single Hop IPv6 ICMP](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md), @PeterKietzmann
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02)
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03)
- [x] [04-Single Hop 6LoWPAN ICMP](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md), @PeterKietzmann
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02)
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03)
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04)
- [x] [05-Single Hop Route](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md), @PeterKietzmann
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md#task-01)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md#task-02)
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md#task-03)
- [x] [06-Single Hop UDP](https://github.com/RIOT-OS/Release-Specs/blob/master/06-single-hop-udp/06-single-hop-udp.md), @PeterKietzmann
- [x] [07-Multi Hop](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-01) @cgundogan
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-02) @cgundogan
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-03) @cgundogan
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-04) @cgundogan
- [x] [08-Interop](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-01), @PeterKietzmann
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-02), @PeterKietzmann
  - ~~Task 03~~
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-04), @smlng
  - [x] [Task 05](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-05), @smlng
  - [x] [Task 06](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-06), @smlng
  - [x] [Task 07](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-07), @smlng
  - ~~Task 08~~
  - [x] [Task 09](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-09), @PeterKietzmann
  - ~~Task 10~~

**Comment by kb2ma** [comment]
My [functional tests](https://github.com/kb2ma/RIOT/wiki/Functional-Tests) for gcoap all passed on both native via TAP and samr21 via TUN (tunslip).

**Comment by smlng** [comment]
08-Interop, Task 04 was successful with following results:

* payload 10B, interval 10ms 9% packet loss
* payload 100B, interval 100ms, 18% packet loss
* payload 1000B, interval 1000ms, 61% packet loss

_NOTE_: real wireless (15.4) connection between Raspberry Pi with Openlabs transceiver and SAMR21-Xpro, default channel settings (26, 0x23) distance approx. 2m.

Software:

* Raspberry Pi: radvd 
* RIOT: GNRC networking

**Comment by smlng** [comment]
08-Interop, Tasks 06 and 07 were successful, test with SAMR21-Xpro and RasPi as 6LBR

* UDP with 8B both directions
* UDP with 200B from host to RIOT only, because shell in GNRC networking has 128 char limit

**Comment by smlng** [comment]
08-Interop, Task 05 successful, but somewhat unstable:

* ping between host and RIOT via RIOT 6LBR worked with approx. 8% packet loss
* 6LBR stops forwarding packets and does not respond to direct pings, though shell indicates no error on 6LBR
* had to try several times until pings got through and were forwarded correctly

**Comment by smlng** [comment]
08-Interop, Task 05, second run more successful :)

* ping works in both directions, packet loss between 1 - 10%
* still: forwardings stopped (sometimes) for several seconds before self recovering

**Comment by PeterKietzmann** [comment]
Thanks @kb2ma! @miri64 can you comment on @smlng's RIOT 6LBR results? Is this "known" issue? Do you remember results of your last release testing?

**Comment by PeterKietzmann** [comment]
Outcome of [01-CI/Task-01](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-01):
```
Errors:

riot_and_cpp:native:
Building application "riot_and_cpp" for "native" with MCU "native".

In file included from /home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/cpp_class.hpp:26:0,
                 from /home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/cpp_class.cpp:23:
/usr/include/c++/4.9/cstdio:41:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/bin/native/riot_and_cpp/cpp_class.o' failed
make[1]: *** [/home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/bin/native/riot_and_cpp/cpp_class.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/main.cpp:33:0:
/usr/include/c++/4.9/cstdio:41:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/bin/native/riot_and_cpp/main.o' failed
make[1]: *** [/home/localadmin/RIOT_RC2/RIOT/examples/riot_and_cpp/bin/native/riot_and_cpp/main.o] Error 1
/home/localadmin/RIOT_RC2/RIOT/Makefile.include:275: recipe for target 'all' failed
make: *** [all] Error 2


cpp11_condition_variable:native:
Building application "tests_cpp11_condition_variable" for "native" with MCU "native".

In file included from /home/localadmin/RIOT_RC2/RIOT/tests/cpp11_condition_variable/main.cpp:21:0:
/usr/include/c++/4.9/string:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
In file included from /home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat/thread.cpp:24:0:
/usr/include/c++/4.9/system_error:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_condition_variable/bin/native/tests_cpp11_condition_variable/main.o' failed
make[1]: *** [/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_condition_variable/bin/native/tests_cpp11_condition_variable/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_condition_variable/bin/native/cpp11-compat/thread.o' failed
make[3]: *** [/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_condition_variable/bin/native/cpp11-compat/thread.o] Error 1
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat' failed
make[2]: *** [ALL--/home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/localadmin/RIOT_RC2/RIOT/sys' failed
make[1]: *** [ALL--/home/localadmin/RIOT_RC2/RIOT/sys] Error 2
/home/localadmin/RIOT_RC2/RIOT/Makefile.include:275: recipe for target 'all' failed
make: *** [all] Error 2


cpp11_mutex:native:
Building application "tests_cpp11_mutex" for "native" with MCU "native".

In file included from /home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat/thread.cpp:24:0:
/usr/include/c++/4.9/system_error:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_mutex/bin/native/cpp11-compat/thread.o' failed
make[3]: *** [/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_mutex/bin/native/cpp11-compat/thread.o] Error 1
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat' failed
make[2]: *** [ALL--/home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/localadmin/RIOT_RC2/RIOT/sys' failed
make[1]: *** [ALL--/home/localadmin/RIOT_RC2/RIOT/sys] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/localadmin/RIOT_RC2/RIOT/Makefile.include:275: recipe for target 'all' failed
make: *** [all] Error 2


cpp11_thread:native:
Building application "tests_cpp11_thread" for "native" with MCU "native".

In file included from /home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/main.cpp:21:0:
/usr/include/c++/4.9/string:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
In file included from /home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat/thread.cpp:24:0:
/usr/include/c++/4.9/system_error:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/bin/native/tests_cpp11_thread/main.o' failed
make[1]: *** [/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/bin/native/tests_cpp11_thread/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/bin/native/cpp11-compat/thread.o' failed
make[3]: *** [/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/bin/native/cpp11-compat/thread.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/4.9/stdexcept:38:0,
                 from /home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat/condition_variable.cpp:21:
/usr/include/c++/4.9/exception:37:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:70: recipe for target '/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/bin/native/cpp11-compat/condition_variable.o' failed
make[3]: *** [/home/localadmin/RIOT_RC2/RIOT/tests/cpp11_thread/bin/native/cpp11-compat/condition_variable.o] Error 1
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat' failed
make[2]: *** [ALL--/home/localadmin/RIOT_RC2/RIOT/sys/cpp11-compat] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/localadmin/RIOT_RC2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/localadmin/RIOT_RC2/RIOT/sys' failed
make[1]: *** [ALL--/home/localadmin/RIOT_RC2/RIOT/sys] Error 2
/home/localadmin/RIOT_RC2/RIOT/Makefile.include:275: recipe for target 'all' failed
make: *** [all] Error 2


pkg_aversiveplusplus:native:
Building application "tests_pkg_aversiveplusplus" for "native" with MCU "native".

(cd /home/localadmin/RIOT_RC2/RIOT/tests/pkg_aversiveplusplus/bin/pkg/native/aversiveplusplus && git submodule update --init --recursive)
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
/home/localadmin/RIOT_RC2/RIOT/Makefile.include:275: recipe for target 'all' failed
make: *** [all] Error 1


Outcome:
	success: arduino_hello-world, bindist, ccn-lite-relay, default, dtls-echo, gcoap, gnrc_border_router, gnrc_minimal, gnrc_networking, gnrc_tcp_cli, gnrc_tcp_srv, gnrc_tftp, hello-world, ipc_pingpong, microcoap_server, nanocoap_server, posix_sockets, saul, timer_periodic_wakeup, bitarithm_timings, bloom_bytes, board_calliope-mini, board_microbit, conn_ip, driver_adt7310, driver_at30tse75x, driver_at86rf2xx, driver_bh1750, driver_bme280, driver_bmp180, driver_dht, driver_enc28j60, driver_encx24j600, driver_hdc1000, driver_hih6130, driver_ina220, driver_io1_xplained, driver_isl29020, driver_isl29125, driver_jc42, driver_kw2xrf, driver_l3g4200d, driver_lis3dh, driver_lis3mdl, driver_lpd8808, driver_lps331ap, driver_lsm303dlhc, driver_mag3110, driver_mma8x5x, driver_mpl3115a2, driver_mpu9150, driver_mq3, driver_nrf24l01p_lowlevel, driver_nvram_spi, driver_pcd8544, driver_pir, driver_pn532, driver_sdcard_spi, driver_servo, driver_si70xx, driver_srf02, driver_srf08, driver_tcs37727, driver_tmp006, driver_xbee, emb6, fault_handler, float, fmt_print, gnrc_ipv6_ext, gnrc_sixlowpan, gnrc_sock_ip, gnrc_sock_udp, irq, leds, libfixmath, libfixmath_unittests, lwip, lwip_sock_ip, malloc, minimal, mpu_stack_guard, msg_send_receive, msg_try_receive, mutex_order, mutex_unlock_and_sleep, netdev2_test, netstats_l2, nhdp, od, periph_adc, periph_cpuid, periph_dac, periph_flashpage, periph_gpio, periph_hwrng, periph_i2c, periph_pwm, periph_rtc, periph_rtt, periph_spi, periph_timer, periph_uart, pipe, pkg_cmsis-dsp, pkg_jsmn, pkg_libcoap, pkg_micro-ecc, pkg_micro-ecc-with-hwrng, pkg_oonf_api, pkg_tiny-asn1, pkg_u8g2, posix_semaphore, posix_sleep, pthread, pthread_barrier, pthread_cleanup, pthread_condition_variable, pthread_cooperation, pthread_rwlock, pthread_tls, saul, sched_testing, shell, sizeof_tcb, slip, struct_tm_utility, thread_basic, thread_cooperation, thread_exit, thread_flags, thread_flood, thread_msg, thread_msg_avail, thread_msg_block_w_queue, thread_msg_block_wo_queue, thread_msg_seq, unittests, warn_conflict, xtimer_drift, xtimer_hang, xtimer_longterm, xtimer_msg, xtimer_msg_receive_timeout, xtimer_now64_continuity, xtimer_periodic_wakeup, xtimer_remove, xtimer_reset, xtimer_usleep, zep
	failed: riot_and_cpp, cpp11_condition_variable, cpp11_mutex, cpp11_thread, pkg_aversiveplusplus
Errors: 5 Warnings: 0
```

**Comment by miri64** [comment]
> Thanks @kb2ma! @miri64 can you comment on @smlng's RIOT 6LBR results? Is this "known" issue? Do you remember results of your last release testing?

Not exactly... At least the recovering part is new. But I don't know at the moment if I ever did these tests myself, either :-/. So I guess the safest thing is to check if it's reproducible on 2016.10.

**Comment by smlng** [comment]
08-Interop, Task05, third run with 2 SAMR21-Xpros:

* works more smoothly in both directions
* RIOT -> RIOT 6LBR -> Host 0-1% packet loss
* Host -> RIOT 6LBR -> RIOT 5-10% packet loss

First observation, from host to RIOT exhibits (always) more packet loss. Second: using RasPi as 6LBR is more stable compared to RIOT-based 6LBR. Third: results very subjective to radio device and its antenna; especially when mixing different boards and radio devices. 

However, so far results are reasonable. Btw. I checked against release 2016.10, similar results, so no (new) issues here.
